### ISSUE TITLE
New data upload

### ISSUE THREAD

**Issue by perezkelly** [clld/amsd#38]
Hi all, I'm crawling out from lockdown and returning to the AMSD.

Here is the latest data upload: https://www.dropbox.com/sh/j3qw2ki411s1um3/AAA_vPN1P0JbvVzsS0dnJuKZa?dl=0
The folder Message_sticks_images_all contains all the images
The file records.csv is the latest data

NOTE: I have added two new fields: 'Subtype' and 'Cultural region'

NOTE ALSO: I tried running the Terminal command **amsd to_csv check** that you set up and I got strange results. It returned only five old entries, all of which look well formed, and I also got the message IndexError: list index out of range.

Could it have something to do with the fact that I added two new fields? Anyway, if you find errors please send them all to me so I can fix them.

**Comment by Bibiko** [comment]
@perezkelly Hi, I've fixed the check due to your structural changes.

**I got the following check issues:**

Error: ling_area_2 in line 105 has wrong structure: Chirila: Mandandanji  Glottolog: no code  Austlang: D44: Mandandanji
Error: check lat/long notation in line 105 for "26.4831° S"
Error: check lat/long notation in line 105 for "147.9661° E"
Error: ling_area_1 in line 730 has wrong structure: Chirila: Yolngu  N117.1: Murngin  Glottolog: yuul1239

sim check: source_citation
Curr, Edward M. 1886. The Australian race: It's origin, languages, customs, place of landing in Australia and the routes by which it spread itself over that continent. 5 vols. Vol. 1. Melbourne: John Ferres.
Curr, Edward M. 1887. The Australian race: Its origin, languages, customs, place of landing in Australia and the routes by which it spread itself over that continent. 5 vols. Vol. 3. Melbourne: John Ferres.

sim check: source_citation
Museum collection
Museum Collection

sim check: ling_area
Yugul|N85|Yugul|no code
Yugul|N85|Yugul|yugu1250

sim check: ling_area
Western Arrarnte|C47|Western Arrarnta|west2441
Western Arrarnta|C47|Western Arrarnta|west2441

sim check: ling_area
Gunwinggu|N70|Kune|guma1252
Gunwinggu|N65|Kunwinjku|guma1252

**In addition here the new fields and their content. Please look at consistency:**

_item_subtype:_

1,traditional
2,traditional_context
3,political
4,Unknown
5,unknown
6,traditional_replicative
7,replicative_traditional
8,Uknown
9,traditional_undateable
10,replicative
11,replicative_artistic`

_cultural regions:_

1,unlocalisable
2,Victoria
3,Queensland
4,South Australia
5,NSW
6,QLD
7,QLD_unlocalisable
8,TopEnd
9,NT
10,SA
11,VIC
12,NT_CA
13,SA_unlocalisable
14,TopEnd_tiwi
15,WA_kimberley
16,NT_CA_unlocalisable
17,TopEnd_arnhem_east
18,TopEnd_tiwi_melville
19,TopEnd_arnhem
20,TopEnd_cobourg
21,WA_unlocalisable
22,WA
23,TopEnd_arnhem_west
24,TopEnd_groote
25,TopEnd_Tiwi
26,TopEnd_arnhem_unlocalisable
27,TopEnd_arnhem_east_unlocalisable
28,WA_Pilbara
29,Pilbara
30,TopEnd_arnhem_west_unlocalisable
31,TopEnd_Arnhem_west
32,TopEnd_groote  TopEnd_arnhem_east

Please go through these issues and update `records.tsv`.

**Comment by Bibiko** [comment]
@perezkelly In addition according to the field `Linked Filename` these images can't be found in `Message_sticks_images_all`:

1879-Gatty-Catalogue_of_the_Mayer_Collection.pdf
2002-Wilson-Message_Stick.jpg
MAGNT-ABART1086_01.JPG
MAGNT-ABART1086_02.JPG
MAGNT-ABART1086_03.JPG
MAGNT-ABART1086_04.JPG
MAGNT-ABETH0543-July_01.JPG
MAGNT-ABETH0543-July_02.JPG
MAGNT-ABETH0543-July_03.JPG
MAGNT-ABETH0543-July_04.JPG
MAGNT-ABETH0543-July_05_cat.JPG
MAGNT-ABETH0543-July_06_cat.JPG
MAGNT-ABETH0650_Barney_01.JPG
MAGNT-ABETH0650_Barney_02.JPG
MAGNT-ABETH0650_Barney_03.JPG
MAGNT-ABETH0650_Barney_04.JPG
MAGNT-ABETH0650_Barney_05.JPG
MAGNT-ABETH0650_Barney_06.JPG
MAGNT-ABETH0650_Barney_07.JPG
MAGNT-ABETH0650_Barney_08.JPG
MAGNT-ABETH0650_Barney_09-cat.JPG
MAGNT-ABETH0650_Barney_10-cat.JPG
MAGNT-ABETH2725-Djabalada_01.JPG
MAGNT-ABETH2725-Djabalada_02.JPG
MAGNT-ABETH2725-Djabalada_03.JPG
MAGNT-ABETH2725-Djabalada_04.JPG
MAGNT-ABETH2725-Djabalada_05_cat.JPG
MAGNT-ABETH2725-Djabalada_06_cat.JPG
MAGNT-ABETH2727-Djimada_01.JPG
MAGNT-ABETH2727-Djimada_02.JPG
MAGNT-ABETH2727-Djimada_03.JPG
MAGNT-ABETH2727-Djimada_04.JPG
MAGNT-ABETH2727-Djimada_05_cat.JPG
MAGNT-ABETH2727-Djimada_06_cat.JPG
MAGNT-ABETH2785-Cadell_01.JPG
MAGNT-ABETH2785-Cadell_02.JPG
MAGNT-ABETH2785-Cadell_03.JPG
MAGNT-ABETH2785-Cadell_04.JPG
MAGNT-ABETH2785-Cadell_05_cat.JPG
MAGNT-ABETH2785-Cadell_06_cat.JPG
z-1904-Clement-Ethnographical_notes.pdf

**Comment by Bibiko** [comment]
@perezkelly ... and the ID `SAM_A_47132` occurs twice.

**Comment by perezkelly** [comment]
Wonderful, thanks for fixing the check! To run the check myself, do I just
go ahead using the same process? That is 1. Open a Terminal window and 2.
Type in amsd to_csv check  ?

All errors are now fixed except for the following which I would like to
ignore:

Curr, Edward M. 1886. The Australian race: It's origin, languages, customs,
place of landing in Australia and the routes by which it spread itself over
that continent. 5 vols. Vol. 1. Melbourne: John Ferres.
Curr, Edward M. 1887. The Australian race: Its origin, languages, customs,
place of landing in Australia and the routes by which it spread itself over
that continent. 5 vols. Vol. 3. Melbourne: John Ferres.
-> these are two separate sources

sim check: source_citation
Museum collection
Museum Collection
->two research assistants had two different policies. Since I can't do a
simple search and replace in the data-entry interface, I would like to
leave this for now and worry about it later

sim check: ling_area
Gunwinggu|N70|Kune|guma1252
Gunwinggu|N65|Kunwinjku|guma1252
->the difference between these two is legitimate and has to do with the way
languages and names are defined in Western Arnhem Land. Sometimes Kune is
seen to contrast with Kunwinjku and sometimes it doesn't. Regarding the
first record, I know the speaker personally and he calls himself a speaker
of 'Kune'.

*item_subtype:*
*cultural regions:*
*->*This was introduced in order to make it easier for me to isolate
certain kinds of traditional message sticks in Arnhem Land for a grant
application, but it will be useful for other things especially regional
maps. I'm still figuring out the terminology, sof it's OK, I would like to
leave this for now and standardise it later.

The new records.tsv file is now in place

**Comment by Bibiko** [comment]
@perezkelly `To run the check myself, do I just
go ahead using the same process? That is 1. Open a Terminal window and 2.
Type in amsd to_csv check  ?` Yes, of course after reinstalling of the Python package [amsd-data](http://github.com/clld/amsd-data)

Your fixes worked fine except for these still missing media files:
2002-Wilson-Message_Stick.jpg
20201011-invaluable-Davidson-A1.jpg
20201011-invaluable-Davidson-A2.jpg
20201011-invaluable-Davidson-B1.jpg
20201011-invaluable-Davidson-B2.jpg

**Comment by Bibiko** [comment]
in addition, I've found these issues:

`exact coordinates for port essington` in column `techniques`

`Piers kelly` in column `data entry`

`message stick from a private sale` versus `a message stick from a private sale` in column `item type`

`132°09'12.0"e` in column `material`

**Comment by Bibiko** [comment]
@perezkelly ... and look at entry `AKERMAN2014P212` for all columns - I believe there was a shift of the columns

**Comment by perezkelly** [comment]
Changes now made.
The AKERMAN2014P212 entry had some strange corruption that I fixed by
deleting data and then re-adding it in the data entry interface. Don't know
why that should have worked but it did!

By the way, I'm having trouble reinstalling the amsd data package but I'll
first see if I can find a python person to check what I'm doing wrong
first.

**Comment by Bibiko** [comment]
@perezkelly New data are online now.

**Comment by perezkelly** [comment]
Yay!
